### ISSUE TITLE
TG-2022-1Levantamentos Iniciais

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [lufamelli/YAD188G04-MeuDireito#1]
# Objetivo
* Descrevam aqui:
    * Tema do trabalho (exemplo: App para adoção de PETs"
    * Breve descrição da situação problema (exemplo: Desenvolver um app para facilitar a adoção de Pets, tendo  como objetivo subjacente a criação de uma rede social com pessoas interessadas em cuidar de animais de estimação)
 
# Artefatos
Deverá ser postado **um arquivo**, formato PDF, cujo conteúdo deverá ter:
* Scrum Master 
    * Nome
    *  Responsabilidades
* Product Owner
    * Nome
    * Responsabilidades 
* Development Time
    Nome | papel | Responsabilidade 
    --------| ------ |--------------------
     xxx      |          |                               
     yyy      |          |                              
     zzz      |          |

**Comment by lufamelli** [comment]
[TG-2022-1Levantamentos Iniciais.pdf](https://github.com/lufamelli/YAD188G04-MeuDireito/files/8218398/TG-2022-1Levantamentos.Iniciais.pdf)

**Comment by anitajara** [comment]
# Objetivo

Tema do trabalho: APP que exibe duvidas de direito do consumidor

Descrevam aqui:  Desenvolver um app que possibilite a criação de
dúvidas sobre direitos do consumidor, bem como a pesquisa e acesso a dúvidas ja criadas.
